In [2]:
#Devesh Bhogre PB47 Panel-2
#Naiive Bayes Classification

In [3]:
import numpy as np
import pandas as pd

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df.tail(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [6]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
#Gaussian NB
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [8]:
#Training the model
gnb.fit(df,iris.target)
pr = gnb.predict([[5.9,3.0,5.1,1.8]])
pr

array([2])

In [9]:
from sklearn.feature_extraction import DictVectorizer
data = [
    { 'house': 100, 'street': 50, 'shop': 25, 'car': 100, 'tree': 20 },
    { 'house': 5, 'street': 5, 'shop': 0, 'car': 10, 'tree': 500, 'river': 1 }
]
dv = DictVectorizer(sparse = False)
X = dv.fit_transform(data)
y = np.array([1, 0])

X

array([[100., 100.,   0.,  25.,  50.,  20.],
       [ 10.,   5.,   1.,   0.,   5., 500.]])

In [10]:
#Multinomial NB
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X, y) #training

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [11]:
test_data = [
    { 'house': 80, 'street': 20, 'shop': 15, 'car': 70, 'tree': 10, 'river': 1 }
]

In [12]:
pr = mnb.predict(dv.fit_transform(test_data)) 
pr

array([1])

In [13]:
from sklearn.datasets import fetch_20newsgroups
data = fetch_20newsgroups()
train = fetch_20newsgroups(subset='train')
test = fetch_20newsgroups(subset='test')

In [14]:
print(train.target_names[:])
print(train.data[5])

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
From: dfo@vttoulu.tko.vtt.fi (Foxvog Douglas)
Subject: Re: Rewording the Second Amendment (ideas)
Organization: VTT
Lines: 58

In article <1r1eu1$4t@transfer.stratus.com> cdt@sw.stratus.com (C. D. Tavares) writes:
>In article <1993Apr20.083057.16899@ousrvr.oulu.fi>, dfo@vttoulu.tko.vtt.fi (Foxvog Douglas) writes:
>> In article <1qv87v$4j3@transfer.stratus.com> cdt@sw.stratus.com (C. D. Tavares) writes:
>> >In article <C5n3GI.F8F@ulowell.ulowell.edu>, jrutledg@cs.ulowell.edu (John Lawrence Rutledge) writes:
>
>> >> The massive destructive power of many modern weapons, makes the
>> >> cost of an accid

In [15]:
#Multinomial NB
#Pipelined with TfidVectorizer and MultinomialNB 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

model = make_pipeline(TfidfVectorizer(),MultinomialNB())

In [16]:
model.fit(train.data, train.target)
labels = model.predict(test.data)

In [17]:
model.fit(train.data, train.target) #training
labels = model.predict(test.data)  #testing
from sklearn.metrics import accuracy_score
accuracy_score(test.target, labels)

0.7738980350504514

In [18]:
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
pr = model.predict(['Hello the CD ROM is compact '])
pr

array([3])

In [20]:
train.target_names[pr[0]]

'comp.sys.ibm.pc.hardware'